### ISSUE TITLE
Decide what framework to use to make LearnUX website.

### ISSUE THREAD

**Issue by Kimeiga** [uclaacm/UXLA#1]
Static site?
- Jekyll 
- Hugo
- 11ty
- Hexo (if yer chinese)

**Comment by tfukaza** [comment]
I'm voting for Jekyll or Hugo.

**Comment by tfukaza** [comment]
Personally Hugo looks interesting though

**Comment by tfukaza** [comment]
I guess Jekyll then? It seems to be the de facto framework.

**Comment by icevin** [comment]
Are we hosting on github pages?

**Comment by tfukaza** [comment]
> Are we hosting on github pages?

Good question, I'll make a new thread for that

**Comment by tfukaza** [comment]
Executive decision we're using 11ty
